### ISSUE TITLE
This repo could use an explanation

### ISSUE THREAD

**Issue by paulehoffman** [bagder/TRRprefs#2]
Greetings.  Based on the title of this repo, it is an "(unofficial)" set of docs for the TRR. However, nothing in this repo says whether this repo will track the information at Mozilla; knowing that would be helpful. Also, nothing in this repo says whether contributions to this repo will also show up in the Mozilla repo.

In short, it would be good to understand why someone of @bagder's stature would create this repo and how we (the world who cares a lot about the TRR) can use it.

**Comment by bagder** [comment]
Fair enough, I think it deserves a little explanation and motivation. Now it says:

> (unofficial) docs for Firefox TRR - created in lack of official docs covering these details. Meant to help Firefox users and ideally be handed over as a gift to Mozilla if/when they decide to host this info themselves. Daniel wrote the original TRR code for Firefox.

Do you think this clarifies enough?

**Comment by paulehoffman** [comment]
Excellent, thanks!

**Comment by wesinator** [comment]
> Fair enough, I think it deserves a little explanation and motivation. Now it says:
> 
> > (unofficial) docs for Firefox TRR - created in lack of official docs covering these details. Meant to help Firefox users and ideally be handed over as a gift to Mozilla if/when they decide to host this info themselves. Daniel wrote the original TRR code for Firefox.
> 
> Do you think this clarifies enough?

There is documentation at https://wiki.mozilla.org/Trusted_Recursive_Resolver#network.trr.mode

**Comment by bagder** [comment]
Yes, I copied my version into the Mozilla wiki (a while ago) as per the goal of this effort.

Since I know that wikis is the place where you put info to die and never update again, I'm also keeping this repo and version alive just to see how things turn out given a little time...
